export const ROUTES = {
  MAIN: '/',
  USERS: '/users',
  SIGNIN: '/sign-in',
  PROFILE: '/profile',
  ME: '/me'
}

export const ACTION_TYPES = {
  
  // users
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  SORT_USERS_BY_NAME: 'SORT_USERS_BY_NAME',

  // auth
  ON_CHANGE_PHONE: 'ON_CHANGE_PHONE',
  ON_CHANGE_PASSWORD: 'ON_CHANGE_PASSWORD',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT: 'SIGN_OUT',

  // profile
  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  // friends
  ADD_FRIEND_START: 'ADD_FRIEND_START',
  ADD_FRIEND_SUCCESS: 'ADD_FRIEND_SUCCESS',
  ADD_FRIEND_FAILURE: 'ADD_FRIEND_FAILURE',
}